import { auth, db } from './firebase.js';
import { onAuthStateChanged, signOut } from 'https://www.gstatic.com/firebasejs/12.15.0/firebase-auth.js';
import { addDoc, collection, doc, getDoc, getDocs, increment, limit, onSnapshot, orderBy, query, serverTimestamp, setDoc, updateDoc, where, arrayUnion, arrayRemove } from 'https://www.gstatic.com/firebasejs/12.15.0/firebase-firestore.js';

const page=document.body.dataset.page||'';
let me=null, meData={};
const $=(s,r=document)=>r.querySelector(s);
const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'');
const initials=n=>esc(n||'Spark').trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'S';
const avatar=(u,cls='avatar')=>{const d=document.createElement('div');d.className=cls;const name=u?.displayName||u?.username||'Spark user';if(u?.photoURL){const i=document.createElement('img');i.src=u.photoURL;i.alt='';d.append(i)}else d.textContent=initials(name);return d};
const nameOf=u=>u?.displayName||u?.username||'Spark user';
const go=p=>location.assign(p);
function nav(){const current=location.pathname.split('/').pop();const items=[['home.html','🏠','Home'],['discover.html','🌍','Discover'],['create.html','＋','Create'],['messages.html','💬','Messages'],['profile.html','👤','Profile']];const n=document.createElement('nav');n.className='bottom-nav';items.forEach(([href,icon,label])=>{const a=document.createElement('a');a.href=href;a.className='nav-item'+(current===href?' is-active':'');if(label==='Create'){a.className='nav-create';a.textContent='＋'}else{const s=document.createElement('span');s.textContent=icon;const sm=document.createElement('small');sm.textContent=label;a.append(s,sm)}n.append(a)});document.body.append(n)}
function topbar(title='SparkSocial'){const h=document.createElement('header');h.className='topbar';h.innerHTML='';const b=document.createElement('a');b.href='home.html';b.className='brand';b.innerHTML='<span>⚡</span> SparkSocial';h.append(b);const actions=document.createElement('div');actions.className='top-actions';if(title!=='Home'){const back=document.createElement('button');back.className='icon-btn';back.textContent='‹';back.onclick=()=>history.length>1?history.back():go('home.html');actions.append(back)}const no=document.createElement('button');no.className='icon-btn';no.textContent='🔔';no.onclick=()=>go('notifications.html');actions.append(no);h.append(actions);return h}
function state(el,msg){el.replaceChildren();const d=document.createElement('div');d.className='status';d.textContent=msg;el.append(d)}
function errorText(e){return e?.code?`${e.code}: ${e.message}`:'Something went wrong. Please try again.'}
async function userDoc(uid){const s=await getDoc(doc(db,'users',uid));return s.exists()?s.data():{uid}}
async function ensureAuth(){return new Promise(resolve=>{const unsub=onAuthStateChanged(auth,async u=>{unsub();if(!u){go('login.html');return}await u.reload();if(!u.emailVerified){go('verify-email.html');return}me=u;meData=await userDoc(u.uid);resolve(u)})})}
function mount(title=page){document.body.prepend(topbar(title));nav()}
function renderPost(id,p){const a=document.createElement('article');a.className='post';a.dataset.id=id;const head=document.createElement('div');head.className='post-head';const author=document.createElement('button');author.className='author';author.append(avatar({displayName:p.displayName,photoURL:p.photoURL}));const info=document.createElement('span');info.className='author-info';const strong=document.createElement('strong');strong.textContent=p.displayName||'Spark user';const small=document.createElement('small');small.textContent=p.username?`@${p.username}`:'Spark';info.append(strong,small);author.append(info);author.onclick=()=>p.authorId&&go(`profile.html?uid=${encodeURIComponent(p.authorId)}`);head.append(author);a.append(head);const body=document.createElement('div');body.className='post-body';body.textContent=p.text||'';a.append(body);const actions=document.createElement('div');actions.className='post-actions';const like=document.createElement('button');like.className='post-action';like.textContent=`♡ ${p.likesCount||0}`;const comment=document.createElement('button');comment.className='post-action';comment.textContent=`💬 ${p.commentsCount||0}`;const repost=document.createElement('button');repost.className='post-action';repost.textContent=`↻ ${p.repostsCount||0}`;actions.append(like,comment,repost);a.append(actions);const comments=document.createElement('div');comments.className='comments';comments.classList.add('hide');const list=document.createElement('div');const form=document.createElement('form');form.className='comment-form';const input=document.createElement('input');input.placeholder='Add a comment…';input.maxLength=500;const send=document.createElement('button');send.type='submit';send.textContent='➤';form.append(input,send);comments.append(list,form);a.append(comments);like.onclick=async()=>{like.disabled=true;try{const lr=doc(db,'postLikes',`${id}_${me.uid}`);const exists=await getDoc(lr);if(exists.exists()){await updateDoc(doc(db,'posts',id),{likesCount:increment(-1)});await import('https://www.gstatic.com/firebasejs/12.15.0/firebase-firestore.js').then(({deleteDoc})=>deleteDoc(lr))}else{await setDoc(lr,{postId:id,userId:me.uid,createdAt:serverTimestamp()});await updateDoc(doc(db,'posts',id),{likesCount:increment(1)})}}finally{like.disabled=false}};comment.onclick=()=>{comments.classList.toggle('hide');input.focus();if(!comments.dataset.loaded)loadComments(id,list,comments)};form.onsubmit=async e=>{e.preventDefault();const text=input.value.trim();if(!text)return;send.disabled=true;try{await addDoc(collection(db,'posts',id,'comments'),{postId:id,authorId:me.uid,displayName:nameOf(meData),photoURL:meData.photoURL||me.photoURL||'',text,createdAt:serverTimestamp()});await updateDoc(doc(db,'posts',id),{commentsCount:increment(1)});input.value=''}catch(err){alert(errorText(err))}finally{send.disabled=false}};return a}
async function loadComments(postId,list,wrap){wrap.dataset.loaded='1';const q=query(collection(db,'posts',postId,'comments'),orderBy('createdAt','asc'),limit(50));onSnapshot(q,s=>{list.replaceChildren();s.forEach(x=>{const c=x.data(),row=document.createElement('div');row.className='comment';row.append(avatar(c,'avatar'));const box=document.createElement('div');box.className='comment-content';const st=document.createElement('strong');st.textContent=c.displayName||'Spark user';const p=document.createElement('p');p.textContent=c.text||'';box.append(st,p);row.append(box);list.append(row)})})}
async function home(){mount('Home');const root=$('#home');const profile=await userDoc(me.uid);const first=nameOf(profile).split(' ')[0];$('#welcome').textContent=`Welcome back, ${first}.`;const av=$('#composerAvatar');av.replaceChildren(avatar(profile));const form=$('#postForm');const input=$('#postText');$('#postCount').textContent='0 / 2000';input.oninput=()=>$('#postCount').textContent=`${input.value.length} / 2000`;form.onsubmit=async e=>{e.preventDefault();const text=input.value.trim();if(!text)return;const btn=$('#postSubmit');btn.disabled=true;try{await addDoc(collection(db,'posts'),{authorId:me.uid,username:profile.username||'',displayName:nameOf(profile),photoURL:profile.photoURL||'',type:'text',text,media:[],hashtags:[],mentions:[],location:null,likesCount:0,commentsCount:0,repostsCount:0,viewsCount:0,visibility:'public',createdAt:serverTimestamp(),updatedAt:serverTimestamp()});await updateDoc(doc(db,'users',me.uid),{postsCount:increment(1),sparkXP:increment(10),updatedAt:serverTimestamp()});input.value='';$('#postCount').textContent='0 / 2000'}catch(err){alert(errorText(err))}finally{btn.disabled=false}};const feed=$('#feed');state(feed,'Loading your sparks…');const q=query(collection(db,'posts'),orderBy('createdAt','desc'),limit(50));onSnapshot(q,s=>{if(s.empty){state(feed,'No sparks yet. Be the first to share one ⚡');return}const f=document.createDocumentFragment();s.forEach(x=>f.append(renderPost(x.id,x.data())));feed.replaceChildren(f)},e=>state(feed,errorText(e)));}
async function discover(){mount('Discover');const list=$('#users');const search=$('#search');async function load(term=''){state(list,'Loading people…');try{const snap=await getDocs(query(collection(db,'users'),limit(50)));const rows=snap.docs.map(x=>({id:x.id,...x.data()})).filter(u=>u.id!==me.uid).filter(u=>!term||`${u.displayName||''} ${u.username||''}`.toLowerCase().includes(term.toLowerCase()));list.replaceChildren();if(!rows.length){state(list,'No people found.');return}for(const u of rows){const row=document.createElement('div');row.className='user-row';row.append(avatar(u));const grow=document.createElement('div');grow.className='grow';const n=document.createElement('strong');n.textContent=u.displayName||u.username||'Spark user';const p=document.createElement('div');p.className='muted';p.textContent=u.username?`@${u.username}`:'Spark member';grow.append(n,p);const b=document.createElement('button');b.className='pill';const fr=doc(db,'follows',`${me.uid}_${u.id}`);const ex=await getDoc(fr);b.textContent=ex.exists()?'Following':'Follow';b.onclick=async()=>{b.disabled=true;const now=await getDoc(fr);if(now.exists()){await import('https://www.gstatic.com/firebasejs/12.15.0/firebase-firestore.js').then(({deleteDoc})=>deleteDoc(fr));await updateDoc(doc(db,'users',u.id),{followersCount:increment(-1)});await updateDoc(doc(db,'users',me.uid),{followingCount:increment(-1)});b.textContent='Follow'}else{await setDoc(fr,{followerId:me.uid,followingId:u.id,status:'active',createdAt:serverTimestamp()});await updateDoc(doc(db,'users',u.id),{followersCount:increment(1)});await updateDoc(doc(db,'users',me.uid),{followingCount:increment(1)});b.textContent='Following'}b.disabled=false};row.onclick=e=>{if(e.target===b)return;go(`profile.html?uid=${u.id}`)};row.append(grow,b);list.append(row)}}catch(e){state(list,errorText(e))}}search.oninput=()=>load(search.value.trim());load()}
async function create(){mount('Create');const form=$('#createForm');const out=$('#createStatus');form.onsubmit=async e=>{e.preventDefault();const text=$('#createText').value.trim();if(!text){out.className='error';out.textContent='Write something first.';return}const b=$('#createButton');b.disabled=true;try{const p=await userDoc(me.uid);await addDoc(collection(db,'posts'),{authorId:me.uid,username:p.username||'',displayName:nameOf(p),photoURL:p.photoURL||'',type:'text',text,media:[],hashtags:[],mentions:[],location:null,likesCount:0,commentsCount:0,repostsCount:0,viewsCount:0,visibility:'public',createdAt:serverTimestamp(),updatedAt:serverTimestamp()});await updateDoc(doc(db,'users',me.uid),{postsCount:increment(1),sparkXP:increment(10),updatedAt:serverTimestamp()});form.reset();out.className='notice';out.textContent='Your Spark is live ⚡'}catch(err){out.className='error';out.textContent=errorText(err)}finally{b.disabled=false}}}
async function profile(){mount('Profile');const uid=new URLSearchParams(location.search).get('uid')||me.uid;const p=await userDoc(uid);$('#profileName').textContent=nameOf(p);$('#profileUsername').textContent=p.username?`@${p.username}`:'';$('#profileBio').textContent=p.bio||'No bio yet.';$('#followers').textContent=p.followersCount||0;$('#following').textContent=p.followingCount||0;$('#posts').textContent=p.postsCount||0;$('#profileAvatar').replaceChildren(avatar(p,'avatar profile-avatar'));if(uid!==me.uid){const b=$('#profileFollow');b.classList.remove('hide');const fr=doc(db,'follows',`${me.uid}_${uid}`);b.textContent=(await getDoc(fr)).exists()?'Following':'Follow';b.onclick=async()=>{b.disabled=true;const ex=await getDoc(fr);if(ex.exists()){await import('https://www.gstatic.com/firebasejs/12.15.0/firebase-firestore.js').then(({deleteDoc})=>deleteDoc(fr));await updateDoc(doc(db,'users',uid),{followersCount:increment(-1)});b.textContent='Follow'}else{await setDoc(fr,{followerId:me.uid,followingId:uid,status:'active',createdAt:serverTimestamp()});await updateDoc(doc(db,'users',uid),{followersCount:increment(1)});b.textContent='Following'}b.disabled=false}}else $('#profileFollow').classList.add('hide');const feed=$('#profileFeed');const q=query(collection(db,'posts'),where('authorId','==',uid),orderBy('createdAt','desc'),limit(50));onSnapshot(q,s=>{feed.replaceChildren();if(s.empty){state(feed,'No sparks yet.');return}s.forEach(x=>feed.append(renderPost(x.id,x.data())))},e=>state(feed,errorText(e)));}
async function notifications(){mount('Notifications');const list=$('#notificationList');state(list,'Loading notifications…');const q=query(collection(db,'notifications'),where('recipientId','==',me.uid),orderBy('createdAt','desc'),limit(50));onSnapshot(q,s=>{list.replaceChildren();if(s.empty){state(list,'You are all caught up ✨');return}s.forEach(x=>{const n=x.data(),r=document.createElement('div');r.className='user-row';const text=document.createElement('div');text.className='grow';text.textContent=`${n.actorName||'Someone'} ${n.type||'interacted with you'}.`;r.append(text);list.append(r)})},e=>state(list,errorText(e)))}
async function messages(){mount('Messages');const list=$('#conversationList');state(list,'Loading conversations…');const q=query(collection(db,'conversations'),where('participantIds','array-contains',me.uid),orderBy('updatedAt','desc'),limit(50));onSnapshot(q,s=>{list.replaceChildren();if(s.empty){state(list,'No conversations yet. Find someone on Discover to start chatting.');return}s.forEach(x=>{const c=x.data(),row=document.createElement('a');row.href=`messages.html?id=${x.id}`;row.className='user-row';const d=document.createElement('div');d.className='grow';const st=document.createElement('strong');st.textContent=c.lastMessageSenderId===me.uid?'You':(c.lastMessage||'Conversation');const sm=document.createElement('div');sm.className='muted';sm.textContent=c.lastMessage||'Start a conversation';d.append(st,sm);row.append(d);list.append(row)})},e=>state(list,errorText(e)))}
async function settings(){mount('Settings');$('#logout').onclick=()=>signOut(auth).then(()=>go('login.html'));const p=await userDoc(me.uid);$('#settingsName').textContent=nameOf(p);$('#settingsEmail').textContent=me.email||'';}
async function searchPage(){mount('Search');const form=$('#searchForm'),out=$('#searchResults');form.onsubmit=async e=>{e.preventDefault();const term=$('#query').value.trim().toLowerCase();if(!term){state(out,'Type something to search.');return}const s=await getDocs(query(collection(db,'users'),limit(100)));const rows=s.docs.map(x=>({id:x.id,...x.data()})).filter(u=>(u.usernameLower||'').includes(term)||(u.displayNameLower||'').includes(term));out.replaceChildren();rows.forEach(u=>{const r=document.createElement('a');r.href=`profile.html?uid=${u.id}`;r.className='user-row';r.append(avatar(u));const d=document.createElement('div');d.className='grow';d.textContent=`${nameOf(u)} ${u.username?'@'+u.username:''}`;r.append(d);out.append(r)});if(!rows.length)state(out,'No matching people found.')}}
async function live(){mount('Spark Live');const list=$('#liveList');state(list,'Loading live sessions…');const q=query(collection(db,'liveSessions'),where('status','==','live'),orderBy('startedAt','desc'),limit(30));onSnapshot(q,s=>{list.replaceChildren();if(s.empty){state(list,'No one is live right now. Be the first Spark to go live 🔴');return}s.forEach(x=>{const l=x.data(),c=document.createElement('a');c.href=`live.html?id=${x.id}`;c.className='live-card';const d=document.createElement('div');const st=document.createElement('strong');st.textContent=l.title||'Spark Live';const p=document.createElement('div');p.className='muted';p.textContent=`🔴 ${l.viewerCount||0} watching`;d.append(st,p);c.append(d);list.append(c)})},e=>state(list,errorText(e)))}
async function creator(){mount('Creator Studio');const p=await userDoc(me.uid);$('#creatorName').textContent=nameOf(p);$('#creatorXP').textContent=p.sparkXP||0;$('#creatorLevel').textContent=p.sparkLevel||1;$('#creatorFollowers').textContent=p.followersCount||0;$('#creatorPosts').textContent=p.postsCount||0;$('#enableCreator').onclick=async()=>{await setDoc(doc(db,'creatorProfiles',me.uid),{userId:me.uid,enabled:true,category:'General',description:'',totalViews:0,totalLikes:0,totalLiveSessions:0,totalLiveMinutes:0,createdAt:serverTimestamp(),updatedAt:serverTimestamp()},{merge:true});alert('Creator mode enabled ✨')}}
async function settingsGate(){const u=await ensureAuth();if(!u)return;try{if(page==='home')await home();else if(page==='discover')await discover();else if(page==='create')await create();else if(page==='profile')await profile();else if(page==='notifications')await notifications();else if(page==='messages')await messages();else if(page==='settings')await settings();else if(page==='search')await searchPage();else if(page==='live')await live();else if(page==='creator')await creator();else if(page==='about'||page==='privacy')mount(page);else mount(page)}catch(e){console.error(e);const c=document.querySelector('.container');if(c)state(c,errorText(e))}}
settingsGate();
